"""empty message

Revision ID: 19fd40edba93
Revises: 
Create Date: 2025-01-30 03:09:17.393993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19fd40edba93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lon', sa.Float(), nullable=False),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_group_purchase_participants_id', table_name='group_purchase_participants')
    op.drop_table('group_purchase_participants')
    op.drop_index('ix_group_purchases_id', table_name='group_purchases')
    op.drop_table('group_purchases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_purchases',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('group_purchases_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_participants', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='group_purchases_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='group_purchases_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_group_purchases_id', 'group_purchases', ['id'], unique=False)
    op.create_table('group_purchase_participants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('group_buy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_buy_id'], ['group_purchases.id'], name='group_purchase_participants_group_buy_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='group_purchase_participants_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='group_purchase_participants_pkey')
    )
    op.create_index('ix_group_purchase_participants_id', 'group_purchase_participants', ['id'], unique=False)
    op.drop_table('ingredient_requests')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
