"""empty message

Revision ID: 1d76a87b9409
Revises: 
Create Date: 2025-03-16 21:47:38.528221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d76a87b9409'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # spatial_ref_sys 테이블은 건드리지 않음
    op.add_column('group_purchases', sa.Column('original_price', sa.Float(), nullable=False))
    op.add_column('group_purchases', sa.Column('saving_price', sa.Float(), nullable=False))
    op.add_column('group_purchases', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_purchases', 'category')
    op.drop_column('group_purchases', 'saving_price')
    op.drop_column('group_purchases', 'original_price')
    # spatial_ref_sys 테이블은 건드리지 않음
    # ### end Alembic commands ###