"""empty message

Revision ID: 4b8363cf7f39
Revises: 
Create Date: 2025-02-16 16:57:09.759290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8363cf7f39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chatrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_purchase_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_purchase_id'], ['group_purchases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_purchase_id')
    )
    op.create_index(op.f('ix_group_chatrooms_id'), 'group_chatrooms', ['id'], unique=False)
    op.create_table('group_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatroom_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatroom_id'], ['group_chatrooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_chat_messages_id'), 'group_chat_messages', ['id'], unique=False)
    op.create_table('group_chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chatroom_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chatroom_id'], ['group_chatrooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_chat_participants_id'), 'group_chat_participants', ['id'], unique=False)
    op.add_column('ingredients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ingredients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('temp_receipts', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_receipts', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'user_id')
    op.drop_index(op.f('ix_group_chat_participants_id'), table_name='group_chat_participants')
    op.drop_table('group_chat_participants')
    op.drop_index(op.f('ix_group_chat_messages_id'), table_name='group_chat_messages')
    op.drop_table('group_chat_messages')
    op.drop_index(op.f('ix_group_chatrooms_id'), table_name='group_chatrooms')
    op.drop_table('group_chatrooms')
    # ### end Alembic commands ###
