"""empty message

Revision ID: 6883baa48a33
Revises: 
Create Date: 2025-02-10 20:56:28.375439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6883baa48a33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=False),
    sa.Column('location_lon', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('contents', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'transaction', 'sales', ['sale_id'], ['id'])
    op.add_column('users', sa.Column('address_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('zone_no', sa.String(), nullable=False))
    op.add_column('users', sa.Column('location_lat', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('location_lon', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location_lon')
    op.drop_column('users', 'location_lat')
    op.drop_column('users', 'zone_no')
    op.drop_column('users', 'address_name')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_table('sales')
    # ### end Alembic commands ###
