"""empty message

Revision ID: 6a5ba8beb425
Revises: b3f59f1314dc
Create Date: 2025-02-03 16:42:49.594827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5ba8beb425'
down_revision: Union[str, None] = 'b3f59f1314dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('recipes_user_id_fkey', 'recipes', type_='foreignkey')
    op.create_foreign_key(None, 'recipes', 'users', ['creator_id'], ['id'])
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.create_foreign_key('recipes_user_id_fkey', 'recipes', 'users', ['user_id'], ['id'])
    op.drop_column('recipes', 'creator_id')
    # ### end Alembic commands ###
