"""empty message

Revision ID: 8bc058dda1f6
Revises: 7850d19ba053
Create Date: 2025-02-03 16:12:32.137136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc058dda1f6'
down_revision: Union[str, None] = '7850d19ba053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('max_calories', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('max_carbs', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user_profiles', sa.Column('max_protein', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user_profiles', sa.Column('max_fat', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('user_profiles', sa.Column('max_sodium', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('user_profiles', 'preferred_cooking_time')
    op.drop_column('user_profiles', 'cooking_skill')
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_column('users', 'nickname')
    op.add_column('user_profiles', sa.Column('cooking_skill', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('preferred_cooking_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'max_sodium')
    op.drop_column('user_profiles', 'max_fat')
    op.drop_column('user_profiles', 'max_protein')
    op.drop_column('user_profiles', 'max_carbs')
    op.drop_column('user_profiles', 'max_calories')
    # ### end Alembic commands ###
