"""empty message

Revision ID: b3f59f1314dc
Revises: be0578e0fdf5
Create Date: 2025-02-03 16:35:36.046369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f59f1314dc'
down_revision: Union[str, None] = 'be0578e0fdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('nutrition_limits', sa.JSON(), nullable=True))
    op.drop_column('user_profiles', 'max_fat')
    op.drop_column('user_profiles', 'max_carbs')
    op.drop_column('user_profiles', 'max_calories')
    op.drop_column('user_profiles', 'max_protein')
    op.drop_column('user_profiles', 'max_sodium')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('max_sodium', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('max_protein', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('max_calories', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('max_carbs', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('max_fat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'nutrition_limits')
    # ### end Alembic commands ###
