"""empty message

Revision ID: bba2d8a15638
Revises: 17ea6db275af
Create Date: 2025-01-12 20:19:19.798454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bba2d8a15638'
down_revision: Union[str, None] = '17ea6db275af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('q_values', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('q_values', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('q_values', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('q_values', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('q_values', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipes', 'ingredients',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('recipes', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recipes', 'cooking_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recipes', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_profiles', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_profiles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_profiles', 'cooking_skill',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.alter_column('user_profiles', 'cooking_skill',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_profiles', 'updated_at')
    op.drop_column('user_profiles', 'created_at')
    op.alter_column('recipes', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipes', 'cooking_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipes', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recipes', 'ingredients',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('recipes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.alter_column('q_values', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('q_values', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('q_values', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('q_values', 'updated_at')
    op.drop_column('q_values', 'created_at')
    # ### end Alembic commands ###
